name: desafio3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de Teste (CI)
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Testar com Cobertura
        run: |
          pytest --cov=scripts

  # Job de Build Docker
  build_docker:
    runs-on: ubuntu-latest
    needs: test  # Só executa se o job de teste for bem-sucedido

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build Docker Image
        run: |
          docker build -t my-temp-app:latest .
          echo "Docker image built successfully!"

      - name: Run Application in Docker
        run: |
          docker run --rm my-temp-app:latest
