name: Directory Watcher

on:
  push:
    paths:
      - "datalake/raw/**"

jobs:
  directory_watcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute ETL
        run: python main.py

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add datalake/silver/*
          git commit -m "Atualização da camada silver"
          git push
